---
abstract: 'Use L<Dist::Zilla> like ARODLAND does'
author:
  - 'Andrew Rodland <arodland@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-ARODLAND
requires:
  Dist::Zilla: '1'
  Dist::Zilla::Plugin::Authority: '0'
  Dist::Zilla::Plugin::AutoVersion: '0'
  Dist::Zilla::Plugin::CopyFilesFromBuild: '0'
  Dist::Zilla::Plugin::Git::NextVersion: '0'
  Dist::Zilla::Plugin::MetaNoIndex: '0'
  Dist::Zilla::Plugin::OurPkgVersion: '0'
  Dist::Zilla::Plugin::ReadmeFromPod: '0'
  Dist::Zilla::PluginBundle::Basic: '0'
  Dist::Zilla::PluginBundle::Git: '0'
  Dist::Zilla::Role::PluginBundle: '0'
  Moose: '0'
  if: '0'
  perl: v5.10.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-ARODLAND
  homepage: http://metacpan.org/release/Dist-Zilla-PluginBundle-ARODLAND
  license: http://dev.perl.org/licenses/
  repository: git://github.com/arodland/Dist-Zilla-PluginBundle-ARODLAND.git
version: '0.07'
x_authority: cpan:ARODLAND
